# Generated by Django 4.1.7 on 2023-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('subscription', models.CharField(blank=True, choices=[('ПРОБНАЯ', 'ПРОБНАЯ'), ('ТЕЛЕГРАМ', 'ТЕЛЕГРАМ'), ('ПОЧТА И ВАЙБЕР', 'ПОЧТА И ВАЙБЕР'), ('ВСЕ ВКЛЮЧЕНО', 'ВСЕ ВКЛЮЧЕНО')], default='ПРОБНАЯ', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
