# Generated by Django 4.1.7 on 2023-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='FIO',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
