# Generated by Django 4.1.7 on 2023-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_account_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
