# Generated by Django 4.1.7 on 2023-03-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_account_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socnet', models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Viber', 'Viber'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram')], default='Открыто', max_length=15)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('date_begin', models.DateTimeField(auto_now_add=True)),
                ('date_last', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('possibilities', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscription',
        ),
        migrations.AddField(
            model_name='account',
            name='isadmin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('Открыто', 'Открыто'), ('Начато', 'Начато'), ('25%', '25%'), ('На полпути', 'На полпути'), ('Заканчиваю', 'Заканчиваю'), ('Выполнено', 'Выполнено')], default='Открыто', max_length=15)),
                ('deadline', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.account')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.chats')),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.subscription'),
            preserve_default=False,
        ),
    ]
