# Generated by Django 4.1.7 on 2023-03-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_chats_clients_subscription_remove_account_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.subscription'),
        ),
    ]
