# Generated by Django 4.1.7 on 2023-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_account_email_alter_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='to_client',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='socnet',
            field=models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Viber', 'Viber'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram')], default='Telegram', max_length=15),
        ),
    ]
