# Generated by Django 4.1.7 on 2023-03-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_messages_to_client_alter_chats_socnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='date_last',
        ),
    ]
