# Generated by Django 4.1.7 on 2023-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_chats_date_last'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-status', 'deadline']},
        ),
        migrations.AlterField(
            model_name='clients',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
