# Generated by Django 4.1.7 on 2023-05-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['postdate']},
        ),
        migrations.AddField(
            model_name='account',
            name='apiKey',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='account',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='crm.account'),
            preserve_default=False,
        ),
    ]
