# Generated by Django 4.1.7 on 2023-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_chats_socnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
