# Generated by Django 4.1.7 on 2023-05-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_account_sub_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='apiEmailKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='apiKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
