# Generated by Django 4.1.7 on 2023-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_account_apiemailkey_alter_account_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='apiEmailKey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='apiKey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
