# Generated by Django 4.1.7 on 2023-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_account_apiemailkey_alter_account_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='socnet',
            field=models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Email', 'Email')], default='Telegram', max_length=15),
        ),
    ]
