# Generated by Django 4.1.7 on 2023-05-18 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_chats_socnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='date_begin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
