# Generated by Django 4.1.7 on 2023-05-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_chats_date_begin_alter_messages_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='apiEmailKey',
            new_name='userChatId',
        ),
    ]
